version: '3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: delivery-db
      POSTGRES_USER: gorillas-test
      POSTGRES_PASSWORD: gorillas-test
    ports:
      - "5432:5432"
    volumes:
      - /opt/db:/var/lib/postgres/data